### ISSUE TITLE
A request for help

### ISSUE THREAD

**Issue by konglingjie2004** [ai4protein/FSFP#6]
A great job! I tried to work it following the readme but met a traceback when I ran `python retrieve.py -m vectorize -md esm2`.
```
Traceback (most recent call last):
  File "/home/kong/FSFP/Pro-FSFP/retrieve.py", line 5, in <module>
    from fsfp.retrieval import Retriever
  File "/home/kong/FSFP/Pro-FSFP/fsfp/retrieval.py", line 7, in <module>
    from .pipeline import model_names
ImportError: cannot import name 'model_names' from 'fsfp.pipeline' (/home/kong/FSFP/Pro-FSFP/fsfp/pipeline.py)
```
I would greatly appreciate it if my asking could be answered.

**Comment by ai4protein** [comment]
Thank you very much for pointing out the error in our code. That line of code 'from .pipeline import model_names' was unnecessary, and we have updated the code.
